// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi5hQDATcqPYisidn92p-kzeINI-VMJO0',
    appId: '1:981352853260:web:4ffd6aae6e8e72cab92329',
    messagingSenderId: '981352853260',
    projectId: 'waste-reportingapp',
    authDomain: 'waste-reportingapp.firebaseapp.com',
    storageBucket: 'waste-reportingapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlfQ0aQ056EGa-JqT1T98-WgVwA3ObyQM',
    appId: '1:981352853260:android:58347c80b541e293b92329',
    messagingSenderId: '981352853260',
    projectId: 'waste-reportingapp',
    storageBucket: 'waste-reportingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAROg5uAxCu_HRHZlzNyoypbQFnbVYhj1Y',
    appId: '1:981352853260:ios:3a32c6705662c0e2b92329',
    messagingSenderId: '981352853260',
    projectId: 'waste-reportingapp',
    storageBucket: 'waste-reportingapp.firebasestorage.app',
    iosBundleId: 'com.example.civilianapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAROg5uAxCu_HRHZlzNyoypbQFnbVYhj1Y',
    appId: '1:981352853260:ios:3a32c6705662c0e2b92329',
    messagingSenderId: '981352853260',
    projectId: 'waste-reportingapp',
    storageBucket: 'waste-reportingapp.firebasestorage.app',
    iosBundleId: 'com.example.civilianapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi5hQDATcqPYisidn92p-kzeINI-VMJO0',
    appId: '1:981352853260:web:eff6b81da21ecf02b92329',
    messagingSenderId: '981352853260',
    projectId: 'waste-reportingapp',
    authDomain: 'waste-reportingapp.firebaseapp.com',
    storageBucket: 'waste-reportingapp.firebasestorage.app',
  );
}
